config/routes.rb
Rails.application.routes.draw do
  resources :thesubjects do
    member do
      get :visit_1
      get :visit_2
    end
    resources :visits
  end

end

app/models/thesubject.rb
class Thesubject
  include Mongoid::Document
  field :subNumber, type: String
  field :age, type: BigDecimal

  embeds_many :visits
end

app/models/visit.rb
class Visit
  include Mongoid::Document

  #visit 1
  field :dov1
  field :icfDt
  field :sex
  field :cont1

  #visit 2
  field :dov2
  field :vtlSigns
  field :plseRate
  field :weight
  field :height

  embedded_in :thesubject, :inverse_of => :visits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/second_visits_controller.rb
class SecondVisitsController < ApplicationController

  def create
    @thesubject = Thesubject.find(params[:thesubject_id])
    @visit = @thesubject.visits.create!(visit_params)
    redirect_to @thesubject, :notice => 'Visit Created!'
  end

  private
  def visit_params
    params.require(:visit).permit(:dov2, :vtlSigns, :plseRate, :weight, :height)
  end


end

app/controllers/thesubjects_controller.rb
class ThesubjectsController < ApplicationController
  before_action :set_thesubject, only: [:show, :edit, :update, :destroy]

  # GET /thesubjects
  # GET /thesubjects.json
  def index
    @thesubjects = Thesubject.all
  end


  # GET /thesubjects/1
  # GET /thesubjects/1.json
  def show
  end

  def visit_1

  end

  def visit_2

  end


  # GET /thesubjects/new
  def new
    @thesubject = Thesubject.new
  end

  # GET /thesubjects/1/edit
  def edit
  end

  # POST /thesubjects
  # POST /thesubjects.json
  def create
    @thesubject = Thesubject.new(thesubject_params)

    respond_to do |format|
      if @thesubject.save
        format.html { redirect_to @thesubject, notice: 'Thesubject was successfully created.' }
        format.json { render :show, status: :created, location: @thesubject }
      else
        format.html { render :new }
        format.json { render json: @thesubject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thesubjects/1
  # PATCH/PUT /thesubjects/1.json
  def update
    respond_to do |format|
      if @thesubject.update(thesubject_params)
        format.html { redirect_to @thesubject, notice: 'Thesubject was successfully updated.' }
        format.json { render :show, status: :ok, location: @thesubject }
      else
        format.html { render :edit }
        format.json { render json: @thesubject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thesubjects/1
  # DELETE /thesubjects/1.json
  def destroy
    @thesubject.destroy
    respond_to do |format|
      format.html { redirect_to thesubjects_url, notice: 'Thesubject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thesubject
      @thesubject = Thesubject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thesubject_params
      params.require(:thesubject).permit(:subNumber, :age)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def create
    @thesubject = Thesubject.find(params[:thesubject_id])
    @visit = @thesubject.visits.create!(visit_params)
    redirect_to @thesubject, :notice => 'Visit Created!'
  end

  def visit_1

  end

  def visit_2

  end

  private
  def visit_params
    params.require(:visit).permit(:dov1, :icfDt, :sex, :cont1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/second_visit_helper.rb
module SecondVisitHelper
end

app/helpers/second_visits_helper.rb
module SecondVisitsHelper
end

app/helpers/thesubjects_helper.rb
module ThesubjectsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thesubjects/_form.html.erb
<%= form_for(@thesubject) do |f| %>
  <% if @thesubject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thesubject.errors.count, "error") %> prohibited this thesubject from being saved:</h2>

      <ul>
      <% @thesubject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Subject Number' %><br>
    <%= f.text_field :subNumber %>
  </div>
  <div class="field">
    <%= f.label 'Age of the Subject' %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <button name='button' type='submit'>Register Subject</button>
  </div>
<% end %>

app/views/thesubjects/edit.html.erb
<h1>Editing Thesubject</h1>

<%= render 'form' %>

<%= link_to 'Show', @thesubject %> |
<%= link_to 'Back', thesubjects_path %>

app/views/thesubjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Register Subject</h1>

<br/>

<%= link_to 'New Subject', new_thesubject_path %>

<br/>

<br/>

<table>
  <thead>
    <tr>
      <th>Subject Number</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thesubjects.each do |thesubject| %>
      <tr>
        <td><%= thesubject.subNumber %></td>
        <td><%= thesubject.age %></td>
        <td><%= link_to 'Visit 1', thesubject %></td>

        <td><%= link_to 'Edit', edit_thesubject_path(thesubject) %></td>
        <td><%= link_to 'Destroy', thesubject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

      <tr>
        <td><%= link_to 'Visit 2', visit_2_thesubject_path(thesubject) %></td>
      </tr>


  <% end %>

    <br/>




  </tbody>
</table>

<br>

app/views/thesubjects/new.html.erb
<h1>Subject Registration</h1>

<%= render 'form' %>

<%= link_to 'Back', thesubjects_path %>

app/views/thesubjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subnumber:</strong>
  <%= @thesubject.subNumber %>
</p>

<p>
  <strong>Age:</strong>
  <%= @thesubject.age %>
</p>

<h2>Visit 1</h2>

<%= form_for [@thesubject, Visit.update] do |f| %>
    <p><%= f.label 'Date of Visit' %> <%= f.text_field :dov1 %></p>
    <p><%= f.label 'Date the Informed Consent was signed' %> <%= f.text_field :icfDt %> </p>
    <p><%= f.label 'Sex' %> <%= f.text_field :sex %> </p>
    <p><%= f.label 'Continue to Visit 1' %> <%= f.text_field :cont1 %> </p>

    <button name='button' type='submit'>Create Visit 1</button>



<% end %>


<%= link_to 'Edit', edit_thesubject_path(@thesubject) %>
<%= link_to 'Back', thesubjects_path %>

app/views/thesubjects/visit1.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subnumber:</strong>
  <%= @thesubject.subNumber %>
</p>

<p>
  <strong>Age:</strong>
  <%= @thesubject.age %>
</p>

<h2>Visit 1</h2>

<%= form_for [@thesubject, Visit.new] do |f| %>
    <p><%= f.label 'Date of Visit' %> <%= f.text_field :dov1 %></p>
    <p><%= f.label 'Date the Informed Consent was signed' %> <%= f.text_field :icfDt %> </p>
    <p><%= f.label 'Sex' %> <%= f.text_field :sex %> </p>
    <p><%= f.label 'Continue to Visit 1' %> <%= f.text_field :cont1 %> </p>

    <button name='button' type='submit'>Create Visit 1</button>

<% end %>


<%= link_to 'Edit', edit_thesubject_path(@thesubject) %> |
<%= link_to 'Back', thesubjects_path %>

app/views/thesubjects/visit_2.html.erb
<p id="notice"><%= notice %></p>



<h2>Visit 2</h2>

<%= form_for [@thesubject, Visit.new] do |f| %>
    <p><%= f.label 'Date of Visit' %> <%= f.text_field :dov2 %></p>
    <p><%= f.label 'Vital Signs' %> <%= f.text_field :vtlSigns %> </p>
    <p><%= f.label 'Weight' %> <%= f.text_field :weight %> </p>
    <p><%= f.label 'Height' %> <%= f.text_field :height %> </p>

    <button name='button' type='submit'>Create Visit 2</button>


<% end %>


<%= link_to 'Edit', edit_thesubject_path(@thesubject) %>
<%= link_to 'Back', thesubjects_path %>